baseURL: "SithijaHW.github.io" 
title: Sithija Hashendra
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Portfolio
          url: Portfolio/
          weight: 5 
          name: Projects
          url: Projects/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: blog/
          weight: 6
        - name: Articals
          url: articals/
          weight: 1

params:
    description: "Personal website and learning portfolio of Sithija Hashendra. Includes blog posts, academic reflections, projects, and learning goals."
    author: Sithija Hashendra
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: true
    disableSpecial1stPost: false
    disableAnchoredHeadings: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: true
    MainSections: [blog", "projects", "portfolio","courses","data"]
    ShowToc: true
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: true
    UseHugoToc: true
    comments: false
    math: false
    profileMode:
          enabled: true
          title: Sithija Hashendra
          subtitle: "HND Cloud Networking Student | IoT & Cybersecurity Explorer | Building innovative tools & dashboards. "
          imageUrl: "sukuna-pink-3840x2160-16934.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Portfolio
              url: Portfolio/
            - name: Projects
              url: Projects/
            - name: Data
              url: data/
            - name: Learning Plan
              url: Learning Plan/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: blog/
            - name: Articals
              url: articals/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:sithijahashendra01@gmail.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/SithijaHW
        - name: YouTube
          url: https://www.youtube.com/@riotsta3
        - name: Twitter
          url: https://x.com/pmichaillat

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Sithija Hashendra"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2